participant: Outer-Fluid

precice-config-file: precice-config.xml

interfaces:
    - mesh: Outer-Fluid-to-Solid
      patches: [interface]
      read-data: [Sink-Temperature-Solid, Heat-Transfer-Coefficient-Solid]
      write-data: [Sink-Temperature-Outer-Fluid, Heat-Transfer-Coefficient-Outer-Fluid]
