participants:
  Solid:
    directory: Solid
    domain-decomposed: false
    interfaces:
    - material-id: 0
      name: Solid-Interface
      patch: interface
      read-data: [Sink-Temperature-Fluid, Heat-Transfer-Coefficient-Fluid]
      read-mesh: Solid-Interface-Faces
      write-data: [Sink-Temperature-Solid, Heat-Transfer-Coefficient-Solid]
      write-mesh: Solid-Interface-Nodes
    non-linear: false
    solver: Code_Aster
precice-config-file: precice-config.xml
