participant: Inner-Fluid

precice-config-file: precice-config.xml

interfaces:
    - mesh: Inner-Fluid-to-Solid
      patches: [interface]
      read-data: [Sink-Temperature-Solid, Heat-Transfer-Coefficient-Solid]
      write-data: [Sink-Temperature-Inner-Fluid, Heat-Transfer-Coefficient-Inner-Fluid]
