name: Run Testsuite (manual) # Unfortunately, we cannot modify the name: https://github.community/t/github-actions-dynamic-name-of-the-workflow-with-workflow-dispatch/150327
on:
  workflow_dispatch:
    inputs:
      suites:
        description: 'Comma seperated testsuites to execute'
        required: true
        type: string
      build_args:
        description: 'Build arguments'
        required: false
        type: string
      systests_branch:
        description: 'Branch to take the systest from'
        default: 'develop'
        required: true
        type: choice
        options:
            - 'develop'
            - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Report log
      run: |
        echo "Initiated by: ${{ github.actor }}"
        echo "Running systemtests --build_args=${{github.event.inputs.build_args}} --suites=${{github.event.inputs.suites}}"
        echo "Systemtests branch: ${{ github.event.inputs.systests_branch }}"
    - name: Check out Tutorials for systest
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.systests_branch }}
    - name: Log directory
      run: |
        ls -al
        pwd
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: install python depencies
      run: |
        python -m pip install -r ./tools/tests/requirements.txt
    - name: Run tests
      run: |
        cd ./tools/tests
        python systemtests.py --build_args=${{github.event.inputs.build_args}} --suites=${{github.event.inputs.suites}}
        cd ../../
    - name: Archive run files
      uses: actions/upload-artifact@v2
      with:
        name: runs
        path: |
          runs/*